PROJECT=miscellaneous

GENERATED_EXECUTABLES=bin/ordn_bogliste \
                      bin/ordn_filmliste \
                      bin/ordn_tegneserieliste \
                      bin/randomise_lines

GENERATED_SOURCES=bioinformatics \
                  speling.org-tools

SCRIPTS=

